import type { ReactElement } from 'react';
import Head from 'next/head';

function Layout({ children }: { children: ReactElement }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">{children}</main>
        </>
    );
}

export default Layout;
